### ISSUE TITLE
Mishandling of local references to other schemas

### ISSUE THREAD

**Issue by dkolepp** [sirosen/check-jsonschema#17]
I ran the following command:

```bash
[prompt ]$ check-jsonschema --schemafile web/schemas/zdoc-heat-schema.json tests/schemas \
  /osp_heat_templates/expected_pass/test1.yaml
```

The `web/schemas/zdoc-heat-schema.json` schema file contained a reference to another schema:

```yaml
      template:
        $ref: 'heat-schema.json#'
```
My understanding of the JSON pointers is (http://niem.github.io/json/reference/json-schema/references/):
A JSON pointer takes the form of A#B in which:

  *  A is the relative path from the current schema to a target schema. If A is empty, the reference is to a type or property in the same schema, an in-schema reference. Otherwise, the reference is to a different schema, a cross-schema reference.
  *  B is the complete path from the root of the schema to a type or property in the schema. If # in not included or B is empty, the reference is to an entire schema.

So, the `heat-schema.json` schema should be relative to the `web/schemas/zdoc-heat-schema.json`........

The error I got was:
```bash
Traceback (most recent call last):
  File "/home/XXX/git/YYY/dle-hooks/venv/lib64/python3.8/site-packages/jsonschema/validators.py", line 774, in resolve_from_url
    document = self.store[url]
  File "/home/XXX/git/YYY/dle-hooks/venv/lib64/python3.8/site-packages/jsonschema/_utils.py", line 22, in __getitem__
    return self.store[self.normalize(uri)]
KeyError: 'file://./heat-schema.json'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.8/urllib/request.py", line 1507, in open_local_file
    stats = os.stat(localfile)
FileNotFoundError: [Errno 2] No such file or directory: '/heat-schema.json'
```
The error seems to indicate that local schema references are not resolved relative to the location of the local target file.

**Comment by dkolepp** [comment]
Version I found this in:
```
15:13 $ pip list | grep check
check-jsonschema 0.5.1
```

**Comment by dudicoco** [comment]
@sirosen @dkolepp i'm experiencing a similar issue when referencing a remote schema:
```json
"$ref": "https://json.schemastore.org/prometheus.rules.json
```

```sh
jsonschema.exceptions.RefResolutionError: HTTP Error 404: Not Found
```

Would https://github.com/sirosen/check-jsonschema/pull/18 solve this as well?

**Comment by dkolepp** [comment]
@dudicoco - I briefly reviewed that schema, and it's not the same issue as this. Within that schema, I don't see any references to schemas **external** to the schema.  [There are other references to the **definitions** section of the schema.

I was able to use your schema (with pre-commit):
```yaml
  - repo: https://github.com/sirosen/check-jsonschema.git
    rev: 0.6.0
    hooks:
      - id: check-jsonschema
        alias: test-check
        args:
          - "--schemafile"
          - https://json.schemastore.org/prometheus.rules.json

```
and then:
```bash
$> pre-commit run test-check --files </path/to/any/yaml>
Validate files with jsonschema...........................................Failed
- hook id: check-jsonschema
- exit code: 1

Schema validation errors were encountered.
  /path/to/some.yaml::<root>: Additional properties are not allowed ('xxx', 'yyy', 'zzz' were unexpected)
```

**Comment by dudicoco** [comment]
@dkolepp I think you misunderstood the issue which i'm facing.

I have my own local schema and I want to reference `https://json.schemastore.org/prometheus.rules.json` within that schema, this results in an error per my previous reply.

**Comment by dkolepp** [comment]
I did not quite understand.  I did try (I think) what you described, and that also worked for me.

The following is the content of `test.json`, which references your schema in the `parameters` property:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "Heat Template schema for GLS",
  "$id": "/schemas/gls-heat-template.json",
  "description": "A schema to validate GLS Heat Templates",
  "type": "object",
  "properties": {
    "description": {
      "type": "string"
    },
    "heat_template_version": {
      "enum": [
        "2018-03-02"
      ],
      "type": "string"
    },
    "parameters": {
      "$ref": "https://json.schemastore.org/prometheus.rules.json"
    },
    "resources": {
      "type": "object"
    }
  },
  "required": [
    "description",
    "heat_template_version",
    "resources"
  ]
}
```
and changed the previous pre-commit configuration to: `args: ["--schemafile", "test.json"]`,
and the output seemed valid:
```bash
07:36 $ pre-commit run test-check --files test.yaml
Validate files with jsonschema...........................................Failed
- hook id: check-jsonschema
- exit code: 1

Schema validation errors were encountered.
  test.yaml::parameters: Additional properties are not allowed ('builder_network_id', 'public_net_id', 'az' were unexpected)
```
which shows that the parameters section of my document does not conform to the schema from your URL.

Is this similar to what you were describing?

**Comment by dudicoco** [comment]
@dkolepp to recreate the issue:

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "prometheusRules": {
      "$ref": "https://json.schemastore.org/prometheus.rules.json"
    }
  }
}
```

values.yaml:
```yaml
prometheusRules:
  groups:
  - name: test
    rules:
    - alert: test
      expr: |
        absent(up{release="test"} == 1)
      for: 5m
      labels:
        severity: critical
      annotations:
        summary: test
```

```sh
$ pre-commit run check-jsonschema -a
Validate values.....................................................Failed
- hook id: check-jsonschema
- exit code: 1

Traceback (most recent call last):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 774, in resolve_from_url
    document = self.store[url]
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_utils.py", line 22, in __getitem__
    return self.store[self.normalize(uri)]
KeyError: 'https://json.schemastore.org/prometheus.rules'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 777, in resolve_from_url
    document = self.resolve_remote(url)
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 863, in resolve_remote
    with urlopen(uri) as url:
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 214, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 523, in open
    response = meth(req, response)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 632, in http_response
    response = self.parent.error(
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 561, in error
    return self._call_chain(*args)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 494, in _call_chain
    result = func(*args)
  File "/usr/local/Cellar/python@3.9/3.9.6/Frameworks/Python.framework/Versions/3.9/lib/python3.9/urllib/request.py", line 641, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 404: Not Found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/bin/check-jsonschema", line 8, in <module>
    sys.exit(main())
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/check_jsonschema/__init__.py", line 14, in main
    checker.run()
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/check_jsonschema/checker.py", line 51, in run
    validator.validate(instance=doc)
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 352, in validate
    for error in self.iter_errors(*args, **kwargs):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_validators.py", line 282, in properties
    for error in validator.descend(
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_validators.py", line 263, in ref
    for error in validator.descend(instance, resolved):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_validators.py", line 282, in properties
    for error in validator.descend(
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_validators.py", line 81, in items
    for error in validator.descend(item, items, path=index):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_validators.py", line 282, in properties
    for error in validator.descend(
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_validators.py", line 81, in items
    for error in validator.descend(item, items, path=index):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_validators.py", line 337, in oneOf
    errs = list(validator.descend(instance, subschema, schema_path=index))
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 344, in descend
    for error in self.iter_errors(instance, schema):
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 328, in iter_errors
    for error in errors:
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/_validators.py", line 259, in ref
    scope, resolved = validator.resolver.resolve(ref)
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 766, in resolve
    return url, self._remote_cache(url)
  File "/Users/xxxx/.cache/pre-commit/repoj9m3e3g9/py_env-python3.9/lib/python3.9/site-packages/jsonschema/validators.py", line 779, in resolve_from_url
    raise exceptions.RefResolutionError(exc)
jsonschema.exceptions.RefResolutionError: HTTP Error 404: Not Found

**Comment by dkolepp** [comment]
Okay- was able to reproduce this.  I don't think this is quite related, but it is caused by the actual URL being different from the URL identified in the `$id` attribute of the schema itself: 
![image](https://user-images.githubusercontent.com/10145457/139917560-e6aed78d-fbc3-423c-8f9d-d835311e4eac.png)

The `$id` does not end with `.json` but the actual URL does.  So when the validator tries to look up other `$ref` attributes in the schema - it is doing so relative to the the `$id` attribute.  

This is *fixed* by correcting the `$id` attribute of the remote schema....

**Comment by sirosen** [comment]
@dkolepp, thanks for taking the time to look into someone else's issue!
I think you're right, and there's an error in the relevant schema. The `jsonschema` lib is behaving correctly and respecting `$id`, and the contents of that field are incorrect.

We should separate this into a separate bug report. It's not the same as the original issue here (which I'm taking a couple of hours to look at now), and trying to handle both threads in a single issue will make things messy. Especially because it will make tracking harder when we solve and close this issue.

@dudicoco, would you please open a new issue with the bug you are seeing, and enough information for me to reproduce the issue? It seems this is an issue with the schema provided by schemastore, but that doesn't mean that there's nothing we can do. At the very least, we can improve the error presentation in `check-jsonschema` to make it faster and easier to diagnose these sorts of problems. If I have a reproducible example, I can work on the `check-jsonschema` error printing and file an issue or even a PR against schemastore.

**Comment by sirosen** [comment]
I've just completed some work on this, now in `main`.

@dkolepp, would you be willing to try out `main` to see if it works for your case, to confirm resolution of this issue before we close? Assuming it works for you, I'll cut a release.

**Comment by dudicoco** [comment]
Thanks @dkolepp.

I don't think the `$id` is the issue here, you can reference a remote schema with or without the `.json` extension.

Referencing a similar remote schema with an ID without the `.json` extension does not fail: https://json.schemastore.org/cryproj.dev.schema.json

I'm not sure what makes the `promtheus.rules` schema fail, opened a new issue: https://github.com/sirosen/check-jsonschema/issues/22

**Comment by sirosen** [comment]
With this solved in `main`, I'm closing.

That `cryproj` schema you reference [can also be fetched from schemastore without the extension](https://json.schemastore.org/cryproj.dev.schema). So it's not the same case.
The prometheus schema refers to a document which doesn't exist.

**Comment by dudicoco** [comment]
Hi @sirosen and @dkolepp,

I've just tested the local ref functionality and it doesn't seem to work.

values.json:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$defs": {
    "test": {
      "type": "string"
    }
  }
}
```

test.json:
```json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "type": "object",
  "required": ["test"],
  "properties": {
    "test": {
      "$ref": "./values.json#/defs/test"
    }
  }
}
```

error:
```sh
Schema validation errors were encountered.
Traceback (most recent call last):
  File "/Users/xxxx/.cache/pre-commit/repoh14v915x/py_env-python3.9/bin/check-jsonschema", line 8, in <module>
    sys.exit(main())
  File "/Users/xxxx/.cache/pre-commit/repoh14v915x/py_env-python3.9/lib/python3.9/site-packages/check_jsonschema/__init__.py", line 16, in main
    checker.run()
  File "/Users/xxxx/.cache/pre-commit/repoh14v915x/py_env-python3.9/lib/python3.9/site-packages/check_jsonschema/checker.py", line 106, in run
    path = [str(x) for x in err.path] or ["<root>"]
AttributeError: 'list' object has no attribute 'path'
```

**Comment by sirosen** [comment]
`"$ref": "./values.json#/defs/test"` is not a correct reference. In your other schema you named it `$defs`, so it should read
`"$ref": "./values.json#/$defs/test"`.

I was able to use that combination of schemas to validate a file, so it appears to be working fine to me. I'll add it to the testsuite.

**Comment by sirosen** [comment]
I've just released v0.7.0 with the changes for this. If you encounter an issue in which `check-jsonschema` fails where it should succeed, please open a new issue.

It is also very helpful to see the json or yaml input on which things failed. The above error regarding `err.path` accessing a list suggests there might be some interesting case to explore here, but I don't have the necessary information to do so.

**Comment by dudicoco** [comment]
@sirosen i've added `$defs` and still getting the same error message.

I'll open a new issue.
